//
//  Invite.swift
//  Chain
//
//  Created by Michael Rutkowski on 11/29/19.
//  Copyright © 2019 Christian Burke. All rights reserved.
//

import Foundation
import Firebase
import FirebaseFirestore

class Invite {
    var chainID: String = ""
    var dateSent: String = ""
    var expirationDate: String = ""
    var sentBy: String = ""
    var receivedBy: String = ""
    var invitationID: String = ""
    var index: Int = 0
    //var previewImage = ChainImage()
    
    //It would be cool to have general information of Chain appear with invitation
    
    init(_chainID:String, _dateSent:String, _expirationDate:String, _sentBy:String, _receivedBy:String, _invitationID:String, _index: Int){
        self.chainID = _chainID
        self.dateSent = _dateSent
        self.expirationDate = _expirationDate
        self.sentBy = _sentBy
        self.receivedBy = _receivedBy
        self.invitationID = _invitationID //UID generated by Firestore
        self.index = _index //Keeps track of index to start off of when chain is opened from invitation
    }
    
    func removeInvitation(currentUser: String, invitationID: String, error: @escaping (String?)->()) {
        
        let firestoreRef = Firestore.firestore().collection("users").document(currentUser)
        firestoreRef.updateData([
            "invites": FieldValue.arrayRemove([invitationID])
        ]) { (err1) in
            if let error1 = err1 {
                masterNav.showPopUp(_title: "Error deleting invitation", _message: error1.localizedDescription)
                error(error1.localizedDescription)
            }else{
                error(nil)
            }
        }
    }
    
}
